services:
  profile-api:
    container_name: profile-api
    build:
      context: .
      dockerfile: Dockerfile
    image: "profile-api:1.0.4"
    restart: unless-stopped
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${PORT:-8071}:${PORT:-8071}"
    networks:
      - shared-db

networks:
  shared-db:
    external: true